# Generated by Django 3.2.11 on 2022-02-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_group_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='task subject')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='task notes')),
                ('slug', models.SlugField(verbose_name='task slug')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('tag', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not Important')], null=True, verbose_name='tag')),
                ('reason', models.CharField(max_length=255, verbose_name='why this has to be done')),
                ('groups', models.ManyToManyField(blank=True, related_name='items', to='groups.Group', verbose_name='groups')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='task owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task', verbose_name='task parrent')),
            ],
        ),
    ]
