# Generated by Django 3.2.11 on 2022-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='why this has to be done'),
        ),
    ]
